### ISSUE TITLE
problem building cffi projects

### ISSUE THREAD

**Issue by flynn1973** [cffi/cffi#319]
this is primarily on redhat ppc64le, but it seems to be also x86 related.

while trying to install cffi based projects in an venv the following error occours. tried it with bcrypt and cryptography.

````
(cryptography-venv) root@lpgaixmgmtlx01:/scratch/sink/python_crypography_build/cryptography/cryptography-venv>pip3 -vvv install bcrypt
Using pip 21.3.1 from /scratch/sink/python_crypography_build/cryptography/cryptography-venv/lib64/python3.6/site-packages/pip (python 3.6)
... 
  Created temporary directory: /tmp/pip-build-env-amqd5lkb
  Running command /scratch/sink/python_crypography_build/cryptography/cryptography-venv/bin/python3 /scratch/sink/python_crypography_build/cryptography/cryptography-venv/lib64/python3.6/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-amqd5lkb/overlay --no-warn-script-location -v --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel 'cffi>=1.1; python_implementation != '"'"'PyPy'"'"''
  Using pip 21.3.1 from /scratch/sink/python_crypography_build/cryptography/cryptography-venv/lib64/python3.6/site-packages/pip (python 3.6)
    Link requires a different Python (3.6.8 not in: '>=3.7'): https://files.pythonhosted.org/packages/4f/27/b51cc9cebfd53b168b8a187c844e7a67dc523dda76be9b46d532815df284/setuptools-59.7.0-py3-none-any.whl#sha256=0c8d5c36aea600828875ab751c03e2c52624edc8382a88a127e31bd8d860e34b (from https://pypi.org/simple/setuptools/) (requires-python:>=3.7)
   ...
  Collecting setuptools>=40.8.0
    Using cached setuptools-59.6.0-py3-none-any.whl (952 kB)
  Collecting wheel
    Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
  Collecting cffi>=1.1
    Using cached cffi-1.15.0-cp36-cp36m-manylinux_2_17_ppc64le.manylinux2014_ppc64le.whl (450 kB)
  Collecting pycparser
    Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
  Installing collected packages: pycparser, wheel, setuptools, cffi
    Creating /tmp/pip-build-env-amqd5lkb/overlay/bin
    changing mode of /tmp/pip-build-env-amqd5lkb/overlay/bin/wheel to 755
  Successfully installed cffi-1.15.0 pycparser-2.21 setuptools-59.6.0 wheel-0.37.1
  Installing build dependencies ... done
  Running command /scratch/sink/python_crypography_build/cryptography/cryptography-venv/bin/python3 /scratch/sink/python_crypography_build/cryptography/cryptography-venv/lib64/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpd431s0n1
  Getting requirements to build wheel ... done
  Created temporary directory: /tmp/pip-modern-metadata-39kuiu_8
  Running command /scratch/sink/python_crypography_build/cryptography/cryptography-venv/bin/python3 /scratch/sink/python_crypography_build/cryptography/cryptography-venv/lib64/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmp7xjenwz6
  Traceback (most recent call last):
    File "/scratch/sink/python_crypography_build/cryptography/cryptography-venv/lib64/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
      main()
    File "/scratch/sink/python_crypography_build/cryptography/cryptography-venv/lib64/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/scratch/sink/python_crypography_build/cryptography/cryptography-venv/lib64/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 164, in prepare_metadata_for_build_wheel
      return hook(metadata_directory, config_settings)
    File "/tmp/pip-build-env-amqd5lkb/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 174, in prepare_metadata_for_build_wheel
      self.run_setup()
    File "/tmp/pip-build-env-amqd5lkb/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 158, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 76, in <module>
      cmdclass={"test": PyTest},
    File "/tmp/pip-build-env-amqd5lkb/overlay/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib64/python3.6/distutils/core.py", line 108, in setup
      _setup_distribution = dist = klass(attrs)
    File "/tmp/pip-build-env-amqd5lkb/overlay/lib/python3.6/site-packages/setuptools/dist.py", line 463, in __init__
      for k, v in attrs.items()
    File "/usr/lib64/python3.6/distutils/dist.py", line 281, in __init__
      self.finalize_options()
    File "/tmp/pip-build-env-amqd5lkb/overlay/lib/python3.6/site-packages/setuptools/dist.py", line 837, in finalize_options
      ep(self)
    File "/tmp/pip-build-env-amqd5lkb/overlay/lib/python3.6/site-packages/setuptools/dist.py", line 858, in _finalize_setup_keywords
      ep.load()(self, ep.name, value)
    File "/tmp/pip-build-env-amqd5lkb/overlay/lib64/python3.6/site-packages/cffi/setuptools_ext.py", line 219, in cffi_modules
      add_cffi_module(dist, cffi_module)
    File "/tmp/pip-build-env-amqd5lkb/overlay/lib64/python3.6/site-packages/cffi/setuptools_ext.py", line 49, in add_cffi_module
      execfile(build_file_name, mod_vars)
    File "/tmp/pip-build-env-amqd5lkb/overlay/lib64/python3.6/site-packages/cffi/setuptools_ext.py", line 25, in execfile
      exec(code, glob, glob)
    File "src/build_bcrypt.py", line 21, in <module>
      ffi = FFI()
    File "/tmp/pip-build-env-amqd5lkb/overlay/lib64/python3.6/site-packages/cffi/api.py", line 48, in __init__
      import _cffi_backend as backend
  ModuleNotFoundError: No module named '_cffi_backend'
  Preparing metadata (pyproject.toml) ... error
WARNING: Discarding https://files.pythonhosted.org/packages/d8/ba/21c475ead997ee21502d30f76fd93ad8d5858d19a3fad7cd153de698c4dd/bcrypt-3.2.0.tar.gz#sha256=5b93c1726e50a93a033c36e5ca7fdcd29a5c7395af50a6892f5d9e7c6cfbfb29 (from https://pypi.org/simple/bcrypt/) (requires-python:>=3.6). Command errored out with exit status 1: /scratch/sink/python_crypography_build/cryptography/cryptography-venv/bin/python3 /scratch/sink/python_crypography_build/cryptography/cryptography-venv/lib64/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmp7xjenwz6 Check the logs for full command output.

````

related issue at cryptography: 
https://github.com/pyca/cryptography/issues/7042

**Comment by flynn1973** [comment]
sorry, wrong project...
